"""
Django settings for CharityApp project.

Generated by 'django-admin startproject' using Django 3.2.21.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g*us42l7hq^mxg$in3g9vt0(s$ny)x#e7tk(f(qylla&9!&4m2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-Party Apps
    "rest_framework",
    # "allauth.socialaccount",
    # "allauth.socialaccount.providers.google",

    # Local Apps
    # 'authentication',
]

MIDDLEWARE = [
    # 'cors.middleware.CorsMiddleware', # CORS Middleware used for Cross Origin Resource Sharing
    'django.middleware.security.SecurityMiddleware', # Security Middleware used for security purposes
    'django.contrib.sessions.middleware.SessionMiddleware', # Session Middleware used for session management
    'django.middleware.common.CommonMiddleware', # Common Middleware 
    'django.middleware.csrf.CsrfViewMiddleware', # CSRF Middleware used for Cross Site Request Forgery to prevent malicious attacks
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Authentication Middleware used for authentication purposes
    'django.contrib.messages.middleware.MessageMiddleware', # Message Middleware used for displaying messages
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # XFrameOptions Middleware used for security purposes
]

ROOT_URLCONF = 'CharityApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', # Debug Template Context Processor used for debugging purposes
                'django.template.context_processors.request', # Request Template Context Processor used for request purposes
                'django.contrib.auth.context_processors.auth', # Authentication Template Context Processor used for authentication purposes
                'django.contrib.messages.context_processors.messages', # Messages Template Context Processor used for displaying messages
            ],
        },
    },
]

WSGI_APPLICATION = 'CharityApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ACCOUNT_EMAIL_VERIFICATION = None


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# AUTH_USER_MODEL = 'authentication.CustomUser' # Custom User Model
AUTH_USER_MODEL = 'auth.User'
